### PR TITLE
Add compatibility with Django 1.8+

### PR DESCRIPTION
**Pull request by elprans**
This adds Django 1.8+ compatibility by:

1. Conditionally switching to the new `TEMPLATE` configuration [layout](https://docs.djangoproject.com/en/1.11/ref/templates/upgrading/)
2. Using `transaction.atomic` instead of deprecated and removed `transaction.commit_on_success`
3. Working around the removal of `db.close_connection()`.
4. Switching the urlconf to the new scheme.
5. Using `ctx` instead of `context` as a `modal.html` template argument, as `context` is reserved.
6. Fixing other minor deprecations and incompatibilities.

### CODE REVIEW

**Comment by coderxiang** [comment]
Hi @elprans , do you mind adding more details regarding this changes, like a list of changes you are making?

**Comment by elprans** [comment]
@coderxiang I updated the PR description.

**Comment by jparise** [comment]
@elprans What's the reason behind the database migration?

**Comment by elprans** [comment]
@jparise `manage.py syncdb` is deprecated in 1.8 and removed in 1.9, so we have to use `manage.py migrate` instead. The latter requires a migration file. This is only reevant for new installations.

**Pull request merged**
